### ISSUE TITLE
Unable to build Inference Engine

### ISSUE THREAD

**Issue by soyjorge** [intel/ros_openvino_toolkit#58] opened 2020-01-06 21:56 UTC
While building OpenVINO's DLDT, after entering the command

cmake -DCMAKE_BUILD_TYPE=Release ..

I'm getting the following error:
-- Configuring incomplete, errors occurred!
See also "/home/jorge/code/dldt/inference-engine/build/CMakeFiles/CMakeOutput.log".
See also "/home/jorge/code/dldt/inference-engine/build/CMakeFiles/CMakeError.log".

Is there another way to build the package?

**Comment by LewisLiuPub** [comment] 2020-01-07 01:53
@soyjorge did you try the build process by following [DLDT's Readme](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md)?

**Comment by sradmard** [comment] 2020-02-13 20:43
@soyjorge the problem is that the DLDT package relies on some submodules that you need to initialise.  Then you will be able to build it.
```
cd dldt/inference-engine/
git submodule update --init --recursive
```

**Comment by LewisLiuPub** [comment] 2020-02-20 03:27
Close this issue, please feel free to re-open it if you have more comments.

**Closed by LewisLiuPub** 2020-02-20 03:27 UTC
